### ISSUE TITLE
Throws exception with the version 2021.2

### ISSUE THREAD

**Issue by liuzhcn** [wicketforge/wicketforge#179]
I get the exception message below when the idea starup (version 2021.2)
Cannot create extension without pico container (class=wicketforge.search.MarkupIndex, constructors=[public wicketforge.search.MarkupIndex(com.intellij.util.messages.MessageBus)]), please remove extra constructor parameters

com.intellij.diagnostic.PluginException: Cannot create class wicketforge.search.MarkupIndex (classloader=PluginClassLoader(plugin=PluginDescriptor(name=WicketForge, id=WicketForge, descriptorPath=plugin.xml, path=~/Library/Application Support/JetBrains/IntelliJIdea2021.2/plugins/wicketforge.jar, version=5.0.2, package=null), packagePrefix=null, instanceId=58, state=active))
	at com.intellij.serviceContainer.ComponentManagerImpl.instantiateClass(ComponentManagerImpl.kt:870)
	at com.intellij.openapi.extensions.impl.XmlExtensionAdapter.instantiateClass(XmlExtensionAdapter.java:99)
	at com.intellij.openapi.extensions.impl.XmlExtensionAdapter$SimpleConstructorInjectionAdapter.instantiateClass(XmlExtensionAdapter.java:116)
	at com.intellij.openapi.extensions.impl.XmlExtensionAdapter.createInstance(XmlExtensionAdapter.java:66)
	at com.intellij.openapi.extensions.impl.ExtensionPointImpl.processAdapter(ExtensionPointImpl.java:458)
	at com.intellij.openapi.extensions.impl.ExtensionPointImpl.access$200(ExtensionPointImpl.java:32)
	at com.intellij.openapi.extensions.impl.ExtensionPointImpl$1.next(ExtensionPointImpl.java:365)
	at com.intellij.util.indexing.FileBasedIndexDataInitialization.initAssociatedDataForExtensions(FileBasedIndexDataInitialization.java:70)
	at com.intellij.util.indexing.FileBasedIndexDataInitialization.prepareTasks(FileBasedIndexDataInitialization.java:111)
	at com.intellij.util.indexing.IndexDataInitializer.call(IndexDataInitializer.kt:20)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at com.intellij.util.concurrency.BoundedTaskExecutor.doRun(BoundedTaskExecutor.java:216)
	at com.intellij.util.concurrency.BoundedTaskExecutor.access$200(BoundedTaskExecutor.java:27)
	at com.intellij.util.concurrency.BoundedTaskExecutor$1.execute(BoundedTaskExecutor.java:195)
	at com.intellij.util.ConcurrencyUtil.runUnderThreadName(ConcurrencyUtil.java:213)
	at com.intellij.util.concurrency.BoundedTaskExecutor$1.run(BoundedTaskExecutor.java:184)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:668)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:665)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:665)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: java.lang.NoSuchMethodException: no such constructor: wicketforge.search.MarkupIndex.<init>()void/newInvokeSpecial
	at java.base/java.lang.invoke.MemberName.makeAccessException(MemberName.java:961)
	at java.base/java.lang.invoke.MemberName$Factory.resolveOrFail(MemberName.java:1101)
	at java.base/java.lang.invoke.MethodHandles$Lookup.resolveOrFail(MethodHandles.java:2030)
	at java.base/java.lang.invoke.MethodHandles$Lookup.findConstructor(MethodHandles.java:1264)
	at com.intellij.serviceContainer.ComponentManagerImpl.instantiateClass(ComponentManagerImpl.kt:830)
	... 22 more
Caused by: java.lang.NoSuchMethodError: wicketforge.search.MarkupIndex: method 'void <init>()' not found
	at java.base/java.lang.invoke.MethodHandleNatives.resolve(Native Method)
	at java.base/java.lang.invoke.MemberName$Factory.resolve(MemberName.java:1070)
	at java.base/java.lang.invoke.MemberName$Factory.resolveOrFail(MemberName.java:1098)
	... 25 more

**Comment by bamarc** [comment]
I don't know if this project is still active, so i patched it myself for the meantime. (https://github.com/bamarc/WicketForge/releases/tag/6.0.0)

If any maintainer is still reading this, i would be willing to take over the project to at least keep it compatible with current IntelliJ Releases but i would need your permission to upload new versions to the Jetbrains Repository.

**Comment by zachalsgaard** [comment]
Got the same issue, and I'd be interested in helping, too - even if just for minor bug fixes, etc.

**Comment by minman** [comment]
I would be happy if the plugin continues to be maintained, unfortunately I don't have the time.
@bamarc I've send you a invitation to join wicketforge. If you also want to upload the plugin to plugins.jetbrains.com, just let me know your username so that I can add you to the developers list there

**Comment by bamarc** [comment]
@minman thank you, my username is the same as here "bamarc".

**Comment by minman** [comment]
@bamarc done. thank you too 👍

**Comment by bamarc** [comment]
New Version 6.0.1 should now be available via Jetbrains Marketplace.
