### ISSUE TITLE
(v6.0.1) PluginException on project init

### ISSUE THREAD

**Issue by bamarc** [wicketforge/wicketforge#181]
Stacktrace:

`com.intellij.diagnostic.PluginException: 'DownloadableLibraryType::getLibraryTypeIcon' isn't overriden or returns 'null' in wicketforge.library.WicketLibraryType [Plugin: WicketForge]
	at com.intellij.ide.plugins.PluginManagerCore.createPluginException(PluginManagerCore.java:274)
	at com.intellij.diagnostic.PluginProblemReporterImpl.createPluginExceptionByClass(PluginProblemReporterImpl.java:12)
	at com.intellij.diagnostic.PluginException.createByClass(PluginException.java:91)
	at com.intellij.framework.library.DownloadableLibraryType.getLibraryTypeIcon(DownloadableLibraryType.java:151)
	at com.intellij.framework.library.DownloadableLibraryType.getIcon(DownloadableLibraryType.java:160)
	at com.intellij.framework.library.DownloadableLibraryType.getIcon(DownloadableLibraryType.java:35)
	at com.intellij.openapi.roots.ui.configuration.libraries.impl.LibraryPresentationManagerImpl$2.processProperties(LibraryPresentationManagerImpl.java:103)
	at com.intellij.openapi.roots.impl.libraries.LibraryDetectionManagerImpl.processProperties(LibraryDetectionManagerImpl.java:30)
	at com.intellij.openapi.roots.ui.configuration.libraries.impl.LibraryPresentationManagerImpl.getCustomIcons(LibraryPresentationManagerImpl.java:98)
	at com.intellij.openapi.roots.ui.configuration.libraries.impl.LibraryPresentationManagerImpl.getCustomIcon(LibraryPresentationManagerImpl.java:86)
	at com.intellij.openapi.roots.ui.configuration.libraries.impl.LibraryPresentationManagerImpl.getNamedLibraryIcon(LibraryPresentationManagerImpl.java:75)
	at com.intellij.openapi.roots.ui.configuration.projectRoot.LibraryConfigurable.getIcon(LibraryConfigurable.java:170)
	at com.intellij.openapi.roots.ui.configuration.projectRoot.ProjectStructureElementRenderer.customizeCellRenderer(ProjectStructureElementRenderer.java:50)
	at com.intellij.ui.ColoredTreeCellRenderer.rendererComponentInner(ColoredTreeCellRenderer.java:122)
	at com.intellij.ui.ColoredTreeCellRenderer.getTreeCellRendererComponent(ColoredTreeCellRenderer.java:54)
	at com.intellij.ui.tree.ui.DefaultTreeUI.getRenderer(DefaultTreeUI.java:172)
	at com.intellij.ui.tree.ui.DefaultTreeUI$2.getNodeDimensions(DefaultTreeUI.java:458)
	at java.desktop/javax.swing.tree.AbstractLayoutCache.getNodeDimensions(AbstractLayoutCache.java:493)
	at java.desktop/javax.swing.tree.VariableHeightLayoutCache$TreeStateNode.updatePreferredSize(VariableHeightLayoutCache.java:1344)
	at java.desktop/javax.swing.tree.VariableHeightLayoutCache$TreeStateNode.expand(VariableHeightLayoutCache.java:1465)
	at java.desktop/javax.swing.tree.VariableHeightLayoutCache$TreeStateNode.expand(VariableHeightLayoutCache.java:1272)
	at java.desktop/javax.swing.tree.VariableHeightLayoutCache.rebuild(VariableHeightLayoutCache.java:728)
	at java.desktop/javax.swing.tree.VariableHeightLayoutCache.treeStructureChanged(VariableHeightLayoutCache.java:629)
	at java.desktop/javax.swing.plaf.basic.BasicTreeUI$Handler.treeStructureChanged(BasicTreeUI.java:4324)
	at java.desktop/javax.swing.tree.DefaultTreeModel.fireTreeStructureChanged(DefaultTreeModel.java:607)
	at java.desktop/javax.swing.tree.DefaultTreeModel.reload(DefaultTreeModel.java:311)
	at com.intellij.openapi.roots.ui.configuration.projectRoot.BaseLibrariesConfigurable.createLibrariesNode(BaseLibrariesConfigurable.java:137)
	at com.intellij.openapi.roots.ui.configuration.projectRoot.BaseLibrariesConfigurable.loadTree(BaseLibrariesConfigurable.java:103)
	at com.intellij.openapi.roots.ui.configuration.projectRoot.BaseStructureConfigurable.loadTreeNodes(BaseStructureConfigurable.java:226)
	at com.intellij.openapi.roots.ui.configuration.projectRoot.BaseStructureConfigurable.reset(BaseStructureConfigurable.java:216)
	at com.intellij.openapi.roots.ui.configuration.projectRoot.BaseLibrariesConfigurable.reset(BaseLibrariesConfigurable.java:97)
	at com.intellij.openapi.roots.ui.configuration.ProjectStructureConfigurable.lambda$reset$1(ProjectStructureConfigurable.java:341)
	at com.intellij.util.io.storage.HeavyProcessLatch.performOperation(HeavyProcessLatch.java:79)
	at com.intellij.openapi.roots.ui.configuration.ProjectStructureConfigurable.reset(ProjectStructureConfigurable.java:327)`

**Comment by bamarc** [comment]
Should be fixed with 6.0.2
